### ISSUE TITLE
Add initial documentation

### ISSUE THREAD

**Issue by tomkerkhove** [CoditEU/BizTalk-Extended#2]
Provide documentation on how to install, what features are included, etc.

**Comment by tomkerkhove** [comment]
Maybe we should consider moving the documentation to a [GitHub Wiki](https://help.github.com/articles/about-github-wikis/)?

**Comment by samneirinck** [comment]
The current docs are fine as far as I can see, only if we need to go more in-depth we could use the wiki indeed.
The only downside is we can't use https://guides.github.com/introduction/flow/index.html, but perhaps that's just a minor thing

**Comment by tomkerkhove** [comment]
I agree.

Seems like we're good for the initial release although we might want some coverage on #4 by @msjonathan? Or am I exagurating?
